BEGIN;
ALTER TABLE nation
DROP CONSTRAINT n_fk1;

ALTER TABLE nation
ADD CONSTRAINT n_fk1 FOREIGN KEY (n_regionkey) REFERENCES region ON DELETE CASCADE;
COMMIT;

BEGIN;
ALTER TABLE supplier
DROP CONSTRAINT s_fk1;

ALTER TABLE supplier
ADD CONSTRAINT s_fk1 FOREIGN KEY (s_nationkey) REFERENCES nation ON DELETE CASCADE;
COMMIT;


BEGIN;
ALTER TABLE partsupp
DROP CONSTRAINT ps_fk1;

ALTER TABLE partsupp
ADD CONSTRAINT ps_fk1 FOREIGN KEY (ps_suppkey) REFERENCES supplier ON DELETE CASCADE;
COMMIT;


BEGIN;
ALTER TABLE customer
DROP CONSTRAINT c_fk1;

ALTER TABLE customer
ADD CONSTRAINT c_fk1 FOREIGN KEY (c_nationkey) REFERENCES nation ON DELETE SET NULL;
COMMIT;

BEGIN;
ALTER TABLE lineitem
DROP CONSTRAINT l_fk1;

ALTER TABLE lineitem
ADD CONSTRAINT l_fk1 FOREIGN KEY (l_partkey, l_suppkey) REFERENCES partsupp ON DELETE SET NULL;
COMMIT;

